spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tickerapi
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    url: /openapi/openapi.yml

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
  ttl-seconds: 3600

massive:
  api:
    base-url: https://api.massive.com
    key: ${POLYGON_API_KEY}